name: backend
on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/backend.yml
      - Dockerfile.backend
  pull_request:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/backend.yml
      - Dockerfile.backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: backend
          args: --modules-download-mode=readonly
      - name: Test
        run: |
          sudo apt update && sudo apt install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswscale-dev
          cd ${{ github.workspace }}/backend && go test -timeout=60s -covermode=count -coverprofile=${{ github.workspace }}/profile.cov_tmp ./...
          cat ${{ github.workspace }}/profile.cov_tmp | grep -v "_mock.go" > ${{ github.workspace }}/profile.cov
      - name: Submit coverage
        run: |
          GO111MODULE=off go get -u -v github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=${{ github.workspace }}/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - name: secrets
        run: |
          wget --content-disposition https://lafin.me/secret.json.gpg
          secret=$(gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.SECRET_PASSPHRASE }} secret.json.gpg)
          dockerUser=`echo $secret | jq -r '.common."docker-user"'`
          echo "::add-mask::$dockerUser"; echo "DOCKER_USER=$dockerUser" >> $GITHUB_ENV
          dockerToken=`echo $secret | jq -r '.common."docker-token"'`
          echo "::add-mask::$dockerToken"; echo "DOCKER_TOKEN=$dockerToken" >> $GITHUB_ENV
      - name: Build image
        run: |
          REPOSITORY=ghcr.io/${{ github.repository }}-api
          docker build --build-arg VERSION=${{ github.ref }}:${{ github.sha }} -t $REPOSITORY -f Dockerfile.backend .
      - name: Publish image
        if: github.ref == 'refs/heads/master'
        run: |
          REPOSITORY=ghcr.io/${{ github.repository }}-api
          echo ${{ env.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ env.DOCKER_USER }} --password-stdin
          docker push $REPOSITORY
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: secrets
        run: |
          wget --content-disposition https://lafin.me/secret.json.gpg
          secret=$(gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.SECRET_PASSPHRASE }} secret.json.gpg)
          digitaloceanClusterName=`echo $secret | jq -r '.common."digitalocean-cluster-name"'`
          echo "::add-mask::$digitaloceanClusterName"; echo "DIGITALOCEAN_CLUSTER_NAME=$digitaloceanClusterName" >> $GITHUB_ENV
          digitaloceanAccessToken=`echo $secret | jq -r '.common."digitalocean-access-token"'`
          echo "::add-mask::$digitaloceanAccessToken"; echo "DIGITALOCEAN_ACCESS_TOKEN=$digitaloceanAccessToken" >> $GITHUB_ENV
          dockerUser=`echo $secret | jq -r '.common."docker-user"'`
          echo "::add-mask::$dockerUser"; echo "DOCKER_USER=$dockerUser" >> $GITHUB_ENV
          dockerToken=`echo $secret | jq -r '.common."docker-token"'`
          echo "::add-mask::$dockerToken"; echo "DOCKER_TOKEN=$dockerToken" >> $GITHUB_ENV
          sshPrivateKey=`echo $secret | jq -r '.common."ssh-private-key"[]'`
          while read line; do echo "::add-mask::$line"; done < <(echo "$sshPrivateKey")
          echo "SSH_PRIVATE_KEY<<EOF
          $sshPrivateKey
          EOF" >> $GITHUB_ENV
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy
        run: |
          DIGITALOCEAN_CLUSTER_IP=$(doctl compute droplet get ${{ env.DIGITALOCEAN_CLUSTER_NAME }} --template {{.PublicIPv4}})
          ssh-keyscan $DIGITALOCEAN_CLUSTER_IP >> $HOME/.ssh/known_hosts
          doctl compute ssh ${{ env.DIGITALOCEAN_CLUSTER_NAME }} --ssh-command " \
            echo ${{ env.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ env.DOCKER_USER }} --password-stdin
            docker-compose -f infra/docker-compose.${{ env.DIGITALOCEAN_CLUSTER_NAME }}.yml pull video-thumbnail-api; \
            docker-compose -f infra/docker-compose.${{ env.DIGITALOCEAN_CLUSTER_NAME }}.yml up -d video-thumbnail-api; \
          "


