name: frontend
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env variables
        run: |
          echo "TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
          echo "REPOSITORY=${REPOSITORY:-$GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "DOCKER_USER=${DOCKER_USER:-$GITHUB_ACTOR}" >> $GITHUB_ENV
        env:
          REPOSITORY: ${{ secrets.REPOSITORY }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: Build image
        run: |
          docker build --build-arg VERSION=$GITHUB_REF:$GITHUB_SHA -t $REPOSITORY-web -f Dockerfile.frontend .
      - name: Publish image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u $DOCKER_USER -p ${{ secrets.DOCKER_TOKEN }}
          docker tag $REPOSITORY-web $REPOSITORY-web:$TAG
          docker push $REPOSITORY-web
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: false # template
    steps:
      - uses: actions/checkout@v2
      - name: Set env variables
        run: |
          echo "REPOSITORY=${REPOSITORY:-$GITHUB_REPOSITORY}" >> $GITHUB_ENV
        env:
          REPOSITORY: ${{ secrets.REPOSITORY }}
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy
        run: |
          ssh-keyscan ${{ secrets.DIGITALOCEAN_CLUSTER_IP }} >> $HOME/.ssh/known_hosts
          doctl compute ssh ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }} --ssh-command " \
            docker-compose -f infra/services/template-go-react/docker-compose.yml pull; \
            docker-compose -f infra/services/template-go-react/docker-compose.yml up -d $REPOSITORY-web; \
          "

